---
 - name: Hardening sshd service
   lineinfile:
     path: /etc/ssh/sshd_config
     regexp: "{{ item.regexp }}"
     line: "{{ item.line }}"
     state: present
   loop:
     - regexp: "^PermitRootLogin"
       line: "PermitRootLogin no"
     - regexp: "^PasswordAuthentication"
       line: "PasswordAuthentication no"
     - regexp: "^X11Forwarding"
       line: "X11Forwarding no"
     - regexp: "^PermitEmptyPasswords"
       line: "PermitEmptyPasswords no"


   notify: Restart sshd

